repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-json
    - id: check-yaml
    - id: detect-private-key
    - id: trailing-whitespace
    - id: no-commit-to-branch
      args: [--branch, master]
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: go-mod-tidy
    - id: go-mod-vendor
    - id: go-build
      stages: [push]
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
    - id: terraform_tfsec