" Indentation & tabs
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
autocmd FileType make setlocal noexpandtab

" Display & format
set number
set textwidth=100
set wrapmargin=2
set showmatch

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Browse and scroll
set scrolloff=5
set laststatus=2

" Miscellaneous
set undofile

" Colors
colors murphy

" Spell
set spell spelllang=en_us
hi clear SpellBad
hi SpellBad cterm=underline ctermfg=red
hi clear SpellCap
hi SpellCap cterm=underline ctermfg=blue
hi clear SpellLocal
hi SpellLocal cterm=underline ctermfg=green
hi clear SpellRare
hi SpellRare cterm=underline ctermfg=yellow
