" Colors
colors murphy

" Indentation & tabs
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
autocmd FileType make setlocal noexpandtab
set pastetoggle=<C-p>

" Display & format
set number
set relativenumber " produces hybrid numbers
set textwidth=100
set wrapmargin=2
set showmatch
if exists('+colorcolumn')
  set colorcolumn=101
else
  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>100v.\+', -1)
endif

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Browse and scroll
set scrolloff=5
set laststatus=2

" Open at same line as was last opened
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

" Spell
set spell spelllang=en_us
hi clear SpellBad
hi SpellBad cterm=underline ctermfg=red
hi clear SpellCap
hi SpellCap cterm=underline ctermfg=blue
hi clear SpellLocal
hi SpellLocal cterm=underline ctermfg=green
hi clear SpellRare
hi SpellRare cterm=underline ctermfg=yellow

" Highlight whitespace at ends of lines
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Miscellaneous
set undofile
