" Indentation & tabs
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

" Display & format
set number
set textwidth=100
set wrapmargin=2
set showmatch

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Browse and scroll
set scrolloff=5
set laststatus=2

" Spell
set spell spelllang=en_us

" Miscellaneous
set undofile

" Colors
colors murphy
